CREATE TABLE IF NOT EXISTS prices (
id BIGSERIAL PRIMARY KEY,
symbol TEXT NOT NULL,
ts TIMESTAMPTZ NOT NULL,
open NUMERIC(18,8),
high NUMERIC(18,8),
low NUMERIC(18,8),
close NUMERIC(18,8) NOT NULL,
volume NUMERIC(18,8),
CONSTRAINT uq_prices_symbol_ts UNIQUE(symbol, ts)
);


CREATE TABLE IF NOT EXISTS model_metrics (
id BIGSERIAL PRIMARY KEY,
model_version TEXT NOT NULL,
train_end_ts TIMESTAMPTZ NOT NULL,
mae DOUBLE PRECISION,
rmse DOUBLE PRECISION,
created_at TIMESTAMPTZ DEFAULT NOW()
);